# Generated by Django 5.2.2 on 2025-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
