# Generated by Django 5.2.2 on 2025-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/ape2.jpg', null=True, upload_to='profiles/'),
        ),
    ]
