# Generated by Django 5.2.2 on 2025-10-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_format',
            field=models.CharField(choices=[('standard', 'Standard'), ('reel', 'Reel')], default='standard', max_length=10),
        ),
    ]
